#ifndef  EVENT_TABLE_H
#define EVENT_TABLE_H

//The Number represents Byte
#define EVENT_ID_LENGTH 4

//
//

#define TYPE_START	29
#define SCR_START	14

#define TYPE_CNT_EVENT	0<<TYPE_START
#define TYPE_SIG_EVENT	1<<TYPE_START

//ID Names should be like : <WHO>_<WHAT>_E_ID


//SIGNAL EVENTS

//Light_barrieres

#define TYPE_LIGHT_BARRIER	TYPE_SIG_EVENTS + (1<<SCR_START)	

#define LIGHT_BARRIER_ENTRY_OPEN_E_ID		TYPE_LIGHT_BARRIER	+ 1
#define	LIGHT_BARRIER_ENTRY_CLOSED_E_ID		TYPE_LIGHT_BARRIER	+ 2

#define LIGHT_BARRIER_HEIGHT_OPEN_E_ID		TYPE_LIGHT_BARRIER	+ 3
#define	LIGHT_BARRIER_HEIGHT_CLOSED_E_ID	TYPE_LIGHT_BARRIER	+ 4

#define LIGHT_BARRIER_SWITCH_OPEN_E_ID		TYPE_LIGHT_BARRIER	+ 5
#define	LIGHT_BARRIER_SWITCH_CLOSED_E_ID	TYPE_LIGHT_BARRIER	+ 6

#define LIGHT_BARRIER_EXIT_OPEN_E_ID		TYPE_LIGHT_BARRIER	+ 7
#define LIGHT_BARRIER_EXIT_CLOSED_E_ID		TYPE_LIGHT_BARRIER	+ 8

//Motor

#define TYPE_MOTOR	TYPE_SIG_EVENTS + (2<<SCR_START)

#define MOTOR_START_E_ID	TYPE_MOTOR	+ 1
#define MOTOR_STOP_E_ID		TYPE_MOTOR	+ 2

#define MOTOR_SLOW_E_ID		TYPE_MOTOR	+ 3
#define MOTOR_FAST_E_ID		TYPE_MOTOR	+ 4

#define MOTOR_LEFT_E_ID		TYPE_MOTOR	+ 5
#define MOTOR_RIGHT_E_ID	TYPE_MOTOR	+ 6
	

//Puk Switch
#define TYPE_PUK_SWITCH	TYPE_SIG_EVENTS + (3<<SCR_START)

#define PUK_SWITCH_OPEN_E_ID	TYPE_PUK_SWITCH	+ 1	
#define PUK_SWITCH_CLOSE_E_ID	TYPE_PUK_SWITCH	+ 2

//Height Sensor

#define HEIGHT_SENSOR_MEASURE_START_E_ID			TYPE_PUK_SWITCH	+ 1	
#define HEIGHT_SENSOR_MEASURE_FINISHED_E_ID			TYPE_PUK_SWITCH	+ 2

#define HEIGHT_SENSOR_INDENTIFIED_BARCODE_PUK_E_ID	TYPE_PUK_SWITCH	+ 3
#define HEIGHT_SENSOR_INDENTIFIED_NORMAL_PUK_E_ID	TYPE_PUK_SWITCH	+ 4
#define HEIGHT_SENSOR_INDENTIFIED_HOLE_PUK_E_ID		TYPE_PUK_SWITCH	+ 5
#define HEIGHT_SENSOR_INDENTIFIED_METAL_PUK_E_ID	TYPE_PUK_SWITCH	+ 6

//Signal lights

//Error Events

#define	ERR_ERMERGENCY_STOP_E_ID
#define ERR_UNKNOWN_PUK_E_ID



#endif